# Example YAML for the bare minimum of required elements
swagger: 2.0
info:
  version: "1.0.0"
  title: petstore
paths:
  /users:
    get:
      responses:
        "200":
          description:  Describe the 200 response in more detail
